spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:a123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#zuul:
#  routes:
#    users:
#      path: /myusers/**
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization
#      url: https://downstream
management:
  security:
    enabled: false
#    roles: ADMIN
#security:
#  user:
#    name: admin
#    password: 123456
    
