spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:a123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000