spring:
  application:
    name: microservice-consumer-moive-ribbon # 建议小写
server:
  port: 8010
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:a123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
management:
  port: 22222   #actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
  context-path: /admin   #actuator暴露接口的前缀
  security:
    enabled: true   #actuator是否需要安全保证
    roles: SUPERUSER
security:
  basic:
    enabled: true
    path: /admin    #针对/admin路径进行认证
  user:
    name: admin
    password: password